allowBuilds:
  esbuild: true
  puppeteer: set this to true or false
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.5.2'
  - '@storybook/builder-vite@10.5.2'
  - '@storybook/csf-plugin@10.5.2'
  - '@storybook/react-dom-shim@10.5.2'
  - '@storybook/react-vite@10.5.2'
  - '@storybook/react@10.5.2'
  - storybook@10.5.2
  - vite@8.1.5
patchedDependencies:
  '@storybook/addon-vitest@10.5.2': patches/@storybook__addon-vitest@10.5.2.patch
